[package]
name = "peerd"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.68", features = ["backtrace"] }
clap = { version = "4.0.32", features = ["derive"] }
crc32fast = "1.3.2"
etcd-client = { version = "0.10.2", features = ["tls"] }
futures = "0.3.25"
genetlink = "0.2.3"
log = "0.4.17"
netlink-packet-route = { version = "0.13.0", features = ["rich_nlas"] }
netlink-packet-wireguard = "0.2.1"
once_cell = "1.16.0"
pem = "1.1.0"
rtnetlink = "0.11.0"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
simple_logger = "4.0.0"
tokio = { version = "1.23.0", features = ["full"] }
toml = "0.5.10"
