[package]
name = "peerd"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.68", features = ["backtrace"] }
clap = { version = "4.0.32", features = ["derive"] }
etcd-client = { version = "0.10.2", features = ["tls"] }
log = "0.4.17"
netlink-packet-wireguard = "0.2.1"
pem = "1.1.0"
serde = { version = "1.0.152", features = ["derive"] }
simple_logger = "4.0.0"
tokio = { version = "1.23.0", features = ["full"] }
toml = "0.5.10"
