name: Build

on:
  push:
  workflow_dispatch:
  create:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          default: true

      - run: sudo apt install protobuf-compiler

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features

      - name: Publish
        if: github.event_name == 'create' && github.event.ref.prefix == 'refs/tags/'
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          path: target
